plugin:
    param: 1

app:
    destination_path: /mnt/data
    # this is dispatcher queue
    # it may be plugin queue directly if needed (dispatcher is a plugin)
    queue: 
        name: qc_make
        type: RMQ
        host: rmq
        user: admin
        password: sa
    database:
        type: DBMongo
        host: db
        port: 27017
        db: ai
        collection: history.jobs
